version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.21
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  CSS_MODE: ${CSS_MODE-optimized}
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: ${SENDGRID_DEV_TO-support@parameter1.com}
  YARN_CACHE_FOLDER: /.yarn-cache
  IDENTITYX_API_TOKEN: ${IDENTITYX_API_TOKEN}
  IDENTITYX_GRAPHQL_URI: ${IDENTITYX_GRAPHQL_URI-https://identity-x.parameter1.com/graphql}
  RECAPTCHA_V3_SITE_KEY: ${RECAPTCHA_V3_SITE_KEY}
  RECAPTCHA_V3_SECRET_KEY: ${RECAPTCHA_V3_SECRET_KEY}
  ENABLE_CONTENT_METER: ${ENABLE_CONTENT_METER-false}
  ZERO_BOUNCE_API_KEY: ${ZERO_BOUNCE_API_KEY}
  DEBUG: ${DEBUG-}
  GAM_TRACK_API_KEY: ${GAM_TRACK_API_KEY-}
  ENABLE_NATIVE_X: ${ENABLE_NATIVE_X-false}

x-env-local-dev: &env-local-dev
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10103}
  OEMBED_URI: ${OEMBED_URI-https://host.docker.internal:10402}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10203}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10303}

x-env-leonis: &env-leonis
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.leonis.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.leonis.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.leonis.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.leonis.base.parameter1.com}
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://base-browse.leonis.base.parameter1.com/graphql}

x-env-virgon: &env-virgon
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.virgon.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.virgon.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.virgon.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.virgon.base.parameter1.com}
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://base-browse.virgon.base.parameter1.com/graphql}

x-site-command: &site-cmd
  <<: *node
  entrypoint: ["yarn"]
  command: ["dev"]
  depends_on:
    - maxmind-geoip

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  sab:
    <<: *site-cmd
    working_dir: /root/sites/scienceboard.net
    environment:
      <<: *env
      HOST: www-smg-sab.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9951
      LIVERELOAD_PORT: 19951
      BRAZE_API_KEY: ${BRAZE_API_KEY_SAB}
    hostname: www-smg-sab.dev.parameter1.com
    ports:
      - "9951:80"
      - "19951:19951"

  lab:
    <<: *site-cmd
    working_dir: /root/sites/labpulse.com
    environment:
      <<: *env
      HOST: www-smg-lab.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9952
      LIVERELOAD_PORT: 19952
      BRAZE_API_KEY: ${BRAZE_API_KEY_LAB}
    hostname: www-smg-lab.dev.parameter1.com
    ports:
      - "9952:80"
      - "19952:19952"

  drb:
    <<: *site-cmd
    working_dir: /root/sites/drbicuspid.com
    environment:
      <<: *env
      HOST: www-smg-drb.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9953
      LIVERELOAD_PORT: 19953
      BRAZE_API_KEY: ${BRAZE_API_KEY_DRB}
    hostname: www-smg-drb.dev.parameter1.com
    ports:
      - "9953:80"
      - "19953:19953"

  am:
    <<: *site-cmd
    working_dir: /root/sites/auntminnie.com
    environment:
      <<: *env
      HOST: www-smg-am.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9954
      LIVERELOAD_PORT: 19954
      BRAZE_API_KEY: ${BRAZE_API_KEY_AM}
    hostname: www-smg-am.dev.parameter1.com
    ports:
      - "9954:80"
      - "19954:19954"

  ame:
    <<: *site-cmd
    working_dir: /root/sites/auntminnieeurope.com
    environment:
      <<: *env
      HOST: www-smg-ame.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9955
      LIVERELOAD_PORT: 19955
      BRAZE_API_KEY: ${BRAZE_API_KEY_AM}
    hostname: www-smg-ame.dev.parameter1.com
    ports:
      - "9955:80"
      - "19955:19955"

  ama:
    <<: *site-cmd
    working_dir: /root/sites/auntminnieasia.com
    environment:
      <<: *env
      HOST: www-smg-ama.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9956
      LIVERELOAD_PORT: 19956
      BRAZE_API_KEY: ${BRAZE_API_KEY_AM}
    hostname: www-smg-ama.dev.parameter1.com
    ports:
      - "9956:80"
      - "19956:19956"

  redis:
    tty: true
    image: docker.io/redis:7.0-alpine
    ports:
      - "9957:6379"

  maxmind-geoip:
    <<: *node
    working_dir: /root/services/maxmind-geoip
    entrypoint: ["/root/node_modules/.bin/gulp"]
    environment:
      <<: [*env]
      REDIS_CACHE_URL: redis://redis:6379/0
      MAXMIND_ACCOUNT_ID: ${MAXMIND_ACCOUNT_ID-1234}
      MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}
      EXPOSED_PORT: 9958
      HOST: smg-maxmind-geoip.dev.parameter1.com
    hostname: smg-maxmind-geoip.dev.parameter1.com
    ports:
      - "9958:80"
    depends_on:
      - redis
